### ISSUE TITLE
Items above crates do not show up / crates dont work

### ISSUE THREAD

**Issue by CoachMCSteve** [snowgears/shopbugs#13]
with a lot of crates the item does not show up after a while. a reload does not help, only a restart does bring them back - for a while. Please help !

**Comment by snowgears** [comment]
Are there any errors in the console? Are you using other plugins that remove items to reduce lag on the server?

**Comment by CoachMCSteve** [comment]
No no exceptions in the console and yes i use ClearLag and WildStacker

**Comment by snowgears** [comment]
Try running a separate test server with those 3 plugins installed. If the issue persists, great! We've figured out its one of those two plugins. Then remove ClearLag because my guess is its a problem with WildStacker. If the issue goes away, its a problem with ClearLag. Please do some testing and let me know!

**Comment by snowgears** [comment]
This will be closed until further response from opener of ticket.
