### ISSUE TITLE
[BUG] Dublicated items on top of chest and cant destroy it after update

### ISSUE THREAD

**Issue by websitecareio** [snowgears/shopbugs#302]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Type of bug

Other unexpected behaviour

### Environment

```markdown
- Server Version: 1.18.1
- Shop Version: Tested 1.8.3.2+

- Dynmap - Issue still there even if this plugin is not there
- Towny - Issue still there even if this plugin is not there
- Better portal - Issue still there even if this plugin is not there
```

### Server startup log

-

### Shop config files

-

### Error log (if applicable)

-

### Bug description

After updating plugins and servers (spigot 1.18) to the newest version, some shops display the items twice above the chest. When trying to remove the chest the items stay in the air (it does say the shop was destroyed in chat), but there is still the items in the air and an invisible block that is unremovable.

Removing all config files did not fix the issue and even removing all of the shop data won't remove the floating items.

No log attached because we are unable to keep the server running with blocks flying around, had to revert to the old version. But server startup did not contain any errors. Will try to make a test server where I can reproduce the error. 
Added some screenshots on discord (TheActualZ)

### Steps to reproduce

Update the shop plugin and / or remove a shop places from an old version of the shop plugin (jan 2021 version i belive it is)

### Expected behaviour

-

### Actual behaviour

-

**Comment by websitecareio** [comment]
Made a video of it here where i reproduced the error: https://youtu.be/hm1STlJ085U (10 minutes)

**Comment by snowgears** [comment]
Because you updated from 1.8.2.4 to 1.8.3.4, there were many changes that happened in between these versions; most notably  1.8.2.7 which made all display client side instead of server side. You are seeing duplicates because you still need to delete all of the old server side displays. You can do this with native kill commands on the old displays or by running '/shop item refresh'.

Read more about the client side change here: https://www.spigotmc.org/resources/shop-the-intuitive-shop-plugin.9628/update?update=410382

Please let me know if I can be of any additional help!
