### ISSUE TITLE
[BUG] Shop plugin not initializing

### ISSUE THREAD

**Issue by xYeezy** [snowgears/shopbugs#317]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Type of bug

Compatibility issue, Error in console

### Environment

```markdown
- Server Version: Mohist 320-1.12.2
- Shop Version: 1.8.3.6-legacy
```

### Server startup log

https://paste.gg/p/anonymous/474b5b40f80d4c489b3ca5ace6675409

### Shop config files

https://paste.gg/p/anonymous/7418df68122d479f8cd6d5c24498e315

### Error log (if applicable)

https://paste.gg/p/anonymous/57aa7f6eb51a47ed8905331b3a7e0ed9

### Bug description

Plugin fails to load

### Steps to reproduce

it's in correct location

### Expected behaviour

plugin to start correctly lol

### Actual behaviour

nothing happens, older versions seem to work no problem, I tried Shop-0.8.3.2.jar and shops work

**Comment by snowgears** [comment]
`
java.lang.NoClassDefFoundError: com/snowgears/shop/handler/LogHandler
--
  | at com.snowgears.shop.Shop.onEnable(Shop.java:384) ~[?:?]
  | at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:177) ~[JavaPlugin.class:?]
  | at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:318) [JavaPluginLoader.class:?]
  | at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:399) [SimplePluginManager.class:?]
  | at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:477) [CraftServer.class:?]
  | at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:418) [CraftServer.class:?]
  | at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:383) [MinecraftServer.class:?]
  | at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:315) [nz.class:?]
  | at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:590) [MinecraftServer.class:?]
  | at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]
  | Caused by: java.lang.ClassNotFoundException: Failed to remap class com.snowgears.shop.handler.LogHandler
  | at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:229) ~[PluginClassLoader.class:?]
  | at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:137) ~[PluginClassLoader.class:?]
  | at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:110) ~[PluginClassLoader.class:?]
  | at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_312]
  | at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_312]
  | ... 10 more
  | Caused by: java.lang.IllegalArgumentException
  | at org.objectweb.asm.ClassReader.<init>(ClassReader.java:185) ~[asm-debug-all-5.2.jar:5.2]
  | at org.objectweb.asm.ClassReader.<init>(ClassReader.java:168) ~[asm-debug-all-5.2.jar:5.2]
  | at org.objectweb.asm.ClassReader.<init>(ClassReader.java:439) ~[asm-debug-all-5.2.jar:5.2]
  | at com.mohistmc.bukkit.nms.remappers.MohistClassRepo.findClass0(MohistClassRepo.java:26) ~[MohistClassRepo.class:?]
  | at net.md_5.specialsource.repo.CachingRepo.findClass(CachingRepo.java:46) ~[CachingRepo.class:?]
  | at com.mohistmc.bukkit.nms.remappers.MohistInheritanceProvider.findNormalParents(MohistInheritanceProvider.java:52) ~[MohistInheritanceProvider.class:?]
  | at com.mohistmc.bukkit.nms.remappers.MohistInheritanceProvider.fineParents(MohistInheritanceProvider.java:23) ~[MohistInheritanceProvider.class:?]
  | at com.mohistmc.bukkit.nms.remappers.MohistInheritanceProvider.getParents(MohistInheritanceProvider.java:16) ~[MohistInheritanceProvider.class:?]
  | at com.mohistmc.bukkit.nms.remappers.MohistInheritanceProvider.getParents(MohistInheritanceProvider.java:10) ~[MohistInheritanceProvider.class:?]
  | at com.mohistmc.bukkit.nms.remappers.MohistJarMapping.tryClimb(MohistJarMapping.java:227) ~[MohistJarMapping.class:?]
  | at com.mohistmc.bukkit.nms.remappers.MohistJarRemapper.mapMethodName(MohistJarRemapper.java:148) ~[MohistJarRemapper.class:?]
  | at net.md_5.specialsource.UnsortedRemappingMethodAdapter.visitMethodInsn(UnsortedRemappingMethodAdapter.java:115) ~[SpecialSource-1.8.5.jar:?]
  | at org.objectweb.asm.ClassReader.readCode(ClassReader.java:1496) ~[asm-debug-all-5.2.jar:5.2]
  | at org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1032) ~[asm-debug-all-5.2.jar:5.2]
  | at org.objectweb.asm.ClassReader.accept(ClassReader.java:708) ~[asm-debug-all-5.2.jar:5.2]
  | at org.objectweb.asm.ClassReader.accept(ClassReader.java:521) ~[asm-debug-all-5.2.jar:5.2]
  | at com.mohistmc.bukkit.nms.remappers.MohistJarRemapper.remapClassFile(MohistJarRemapper.java:174) ~[MohistJarRemapper.class:?]
  | at com.mohistmc.bukkit.nms.remappers.MohistJarRemapper.remapClassFile(MohistJarRemapper.java:156) ~[MohistJarRemapper.class:?]
  | at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:193) ~[PluginClassLoader.class:?]
  | at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:137) ~[PluginClassLoader.class:?]
  | at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:110) ~[PluginClassLoader.class:?]
  | at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_312]
  | at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_312]
  | ... 10 more

`

**Comment by snowgears** [comment]
This is interesting. It looks like Mohist is trying to remap but not finding the com/snowgears/shop/handler/LogHandler class?

**Comment by snowgears** [comment]
I believe this is a bug with Mohist and the way it tries to remap classes with overlapping names. Please open a bug with Mohist. If this is something I can help with, happy to reopen the issue, but it appears to be Mohist
