### ISSUE TITLE
[BUG] Shops not reading decimals places

### ISSUE THREAD

**Issue by mythicaleem** [snowgears/shopbugs#375]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Type of bug

Other unexpected behaviour

### Environment

```markdown
- Server Version: Paper 1.19.3 
- Shop Version: 1.8.4.1
```

### Server startup log

https://gist.github.com/mythicaleem/dba8534f24be91fd75112089d4e221a6

### Shop config files

https://gist.github.com/mythicaleem/7986a98a2d15305734fbc81e99a5731d

### Bug description

All shops can not read decimal places and if you try to type on it it tells you that you that is needs to be a positive number.

### Steps to reproduce

1. Click on a chest to create a shop
2. Then tell how many items you are buy/selling
3. Then when it askes for the price give it a number like .03 or 4.24 

### Expected behaviour

In 1.19.2, you are able to use decimal places for shop prices

### Actual behaviour

Players get a alert telling them that on line 3 they must have a positive number.

### Other information

![2022-12-16_18 20 42](https://user-images.githubusercontent.com/120760971/208213274-0127b787-dd08-44a6-8c11-88ad19bac691.png)

**Comment by snowgears** [comment]
Config file values are case sensitive. In your config.yml file, you need to change "Vault" to "VAULT".

You should see at startup what currency type shop loads in as. If it successfully connects to Vault, you will see
` [Shop] Vault dependency found. Using the Vault economy ($) for currency on the server.`

otherwise, it defaults to using Items as the currency where fractions like this would not be allowed.
