### ISSUE TITLE
More Worldguard Integration

### ISSUE THREAD

**Issue by Truongvv10** [snowgears/shopbugs#396]
**Is your feature request related to a problem? Please describe.**
`No`

**Describe the solution you'd like**
`I want people to be able to create shops in their own area protected by worldguard, or even outside of those areas. However, there's an issue where people are able to create shops in the main area protected by worldguard (not their own area), even when the setting is set to not allow shops there.`

**Describe alternatives you've considered**
`Make it so worldguard doesn't necessarily is forcing people to create shops in regions only, but make it so the flag allow-shop is available at all times even with worldguard off, so we can let regions handle it with priorities and stiff`

**Additional context**
`none`

**Comment by OstlerDev** [comment]
I have revamped our WorldGuard integration so that it will now properly respect the flags `passthrough`, `build`, `chest-access`. These checks will now always be performed, and are checked first before the `allow-shop` flag.

The `allow-shop` flag has now been made **optional**!
- **(Default) Ignore Flag**: 
    - Allow shops everywhere that you can build and access chests, and ignore the `allow-shop` flag completely. 
    - Verify `hookWorldGuard` is `false` in your `config.yml` file

- **Require Flag:** 
    - Completely disallow shops in all regions that do not explicitly have `allow-shop: ALLOW`. 
    - Set `hookWorldGuard` to `true` in your `config.yml` file

## All of these changes will be included in the 1.9.0.2 release!

**Comment by OstlerDev** [comment]
Released 1.9.1.0
