### ISSUE TITLE
SignChangeEvent not respecting cancelations

### ISSUE THREAD

**Issue by tWizT3ddreaMr** [snowgears/shopbugs#410]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Type of bug

Other unexpected behaviour

### Environment

```markdown
- Server Version: Purpur 1.20
- Shop Version: newest
```

### Server startup log

If you insist you need this I will get it to you.

### Shop config files

If you insist you need this I will get it to you.

### Bug description

The SignChangeEvent doesnt check if it gets canceled, allowing someone, with how signs edit now even when canceled, to create a shop in a location where they cannot build, or truly edit the signs.

### Steps to reproduce

Have a plugin that would cancel the sign editing, lets say worldguard for this.
Interact with the sign 
Write out the shop creation

### Expected behaviour

It should not go to shop initialization

### Actual behaviour

It does go to shop initialization, and player can effectively lock a chest where they cannot build.

**Comment by OstlerDev** [comment]
I have revamped our WorldGuard integration so that it will now properly respect the flags `passthrough`, `build`, `chest-access`. These checks will now always be performed, and are checked first before the `allow-shop` flag. **This should fix the bug you were running into!**

The `allow-shop` flag has now been made **optional**!
- **(Default) Ignore Flag**: 
    - Allow shops everywhere that you can build and access chests, and ignore the `allow-shop` flag completely. 
    - Verify `hookWorldGuard` is `false` in your `config.yml` file

- **Require Flag:** 
    - Completely disallow shops in all regions that do not explicitly have `allow-shop: ALLOW`. 
    - Set `hookWorldGuard` to `true` in your `config.yml` file

## All of these fixes/changes will be included in the 1.9.0.2 release!

**Comment by OstlerDev** [comment]
Released 1.9.1.0
