### ISSUE TITLE
Limit number of shops permission bug

### ISSUE THREAD

**Issue by Icalave** [snowgears/shopbugs#78]
Describe the bug
i gave the permission node shop.buildlimit.# and they either have infinite or 3 no inbetween.

To Reproduce
give players permission node shop.buildlimit.# and limits enter'd no longer work (I do have UsePerms enabled)

Expected behavior
Limit shops based off users specific permission node

Version:

Spigot version: [Spigot 1.14.4]
Shop version [1.8.1]
Additional context
(We have a unique system were we have a default limit in rank itself then players get a specific perm to unlock more for themselves)

**Comment by snowgears** [comment]
Tested by TechnoRunner as well:

`Here is what I found while using Spigot 1.16.3

Plugins Used:
Shop - v 1.8.2.2
EssentialsX
Luckperms - v 5.1.84
Vault - v1.7.3

All shop permissions still function as intended. I think the problem is conflicting permissions group inheritance.`

If possible, please post a copy of your permissions database.
